services:
  mono-ui:
    image: registry-vpc.cn-beijing.aliyuncs.com/weian404/mono-ui
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8081:80"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 50M
